services:
  webapp:
    build:
      context: .
      args:
        - PUID=1000
        - PGID=1000
    container_name: python_pastebin
    ports:
      - "5000:8000" # Map port 5000 on your computer to port 8000 in the container
    volumes:
      # This links the local 'data' folder to the '/app/data' folder in the container
      - ./data:/app/data
    restart: unless-stopped
